"use client";
// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
import { Box, ChakraProvider, Flex } from "@chakra-ui/react";
import { theme } from "../constants/theme";
import { CounterStoreProvider } from "../../counterStoreProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { TonConnectUIProvider } from "@tonconnect/ui-react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TonConnectUIProvider manifestUrl="http://localhost:3000" >
          <CounterStoreProvider>
            <ChakraProvider theme={theme}>
              <Flex padding={"0 32px"} style={{ height: '100vh' }}>
                {children}
              </Flex>
              <ToastContainer />
            </ChakraProvider>
          </CounterStoreProvider>
        </TonConnectUIProvider>
      </body>
    </html>
  );
}
